Add SingleList to Home component and ListItem to List component
the-collab-lab/tcl-79-smart-shopping-list pull request #19
Opened 2024-08-13 11:44 UTC by marshjaja

## Description

We rendered the shopping list the users have access to. And the name of the items on the list.

## Related Issue
 Issue #2 

## Acceptance Criteria

-  In Home.jsx, the SingleList component is used to render the name of each shopping list a user is subscribed to
 - In List.jsx, the ListItem component is used to render the name of each item

## Type of Changes

Added The Shopping list feature.

## Updates

### Before

N/A

### After

Items displayed

## Testing Steps / QA Criteria

- Do a `git pull` and `git checkout  mm-jo-rendered-list`.
- Open the homepage by running `npm start`.
- Shopping will render on Home component and list items will show in List component.

2024-08-14 09:09 UTC, Wyna-7 requested changes
Great work!

2024-08-14 09:09 UTC, Wyna-7 commented on src/views/Home.jsx
> +				))} */}
If this is not needed, it is best to remove commented out code :)

2024-08-16 12:42 UTC, Hudamabkhoot approved these changes
Well done!

2024-08-16 16:46 UTC, hariscs approved these changes
Good work guys  🎉

2024-08-17 17:25 UTC, merged