Jo qg shopping list filter
the-collab-lab/tcl-79-smart-shopping-list pull request #23
Opened 2024-08-29 11:20 UTC by joriordan332

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description
Implemented a search bar so that our user can filter their shopping list items.

## Related Issue
Closed #7 

## Acceptance Criteria
- [x] A form is added to the top of the `List` view, above the shopping list
- [x] The form includes the following elements
	- A text field (with semantic `<label>`!) which narrows down the list as the user types
	- When there’s text in the field, some kind of button (e.g., an X) to clear the field. When the field is cleared, the list is reset to its unfiltered state.

## Type of Changes
Feature
Use one or more labels to help your team understand the nature of the change(s) you’re proposing. E.g., `bug fix` or `enhancement` are common ones.

## Updates

### Before
![image](https://github.com/user-attachments/assets/5537f467-a0f0-46bd-8a00-ae966dc1e944)

### After
<img width="959" alt="image" src="https://github.com/user-attachments/assets/4e72c5b7-8ad9-434f-b85f-4584e2883fb9">

## Testing Steps / QA Criteria
-Run `git pull` `git checkout jo-qg-shopping-list-filter` 
-Open with `npm start`
-Navigate to `List` to find the search bar
-Items in the list will be filtered according to the user input in the search bar

2024-08-30 13:48 UTC, Hudamabkhoot requested changes
Great work! 👏 I just left a comment about a small change to the filtering for better accuracy.

2024-08-30 13:48 UTC, Hudamabkhoot commented on src/components/SearchBar.jsx
> +	};
Adding .trim() to the search term would help prevent users from filtering with spaces.

2024-08-30 17:13 UTC, hariscs approved these changes

2024-08-31 18:12 UTC, Hudamabkhoot approved these changes

2024-08-31 19:41 UTC, merged