Mm qg predict next purchase
the-collab-lab/tcl-79-smart-shopping-list pull request #27
Opened 2024-09-11 16:50 UTC by marshjaja

## Description

When a new purchase is recorded the next purchase date is automatically computed and the app learn how often the item is purchased.

## Related Issue
Closes #11 

## Acceptance Criteria

- [x] When the user purchases an item, the item’s `dateNextPurchased` property is calculated using the `calculateEstimate` function and saved to the Firestore database
  - [x] `dateNextPurchased` is saved as **a date**, not a number
- [x] A `getDaysBetweenDates` function is exported from `utils/dates.js`  and imported into `api/firebase.js`
  - [x] This function takes two JavaScript Dates and return the number of days that have passed between them

## Type of Changes

enhancement

## Updates

### Before
N/A

### After
N/A

## Testing Steps / QA Criteria
- Do a `git pull` and `git checkout mm-qg-predict-next-purchase`.
- Open the homepage by running `npm start`.
- Navigate to the `List` and check one of the items on the list.
- Check Firestore: the `dateLastPurchased`, `dateNextPurchased` and `dayInterval` should be updated according to how many days have elapsed since the item was last purchased.

2024-09-12 11:14 UTC, joriordan332 approved these changes
Looks great guys! Well done

2024-09-12 11:24 UTC, Hudamabkhoot approved these changes
Amazing work well done!

2024-09-14 15:50 UTC, redapy requested changes
Amazing work handling this issue, well done!!! I left a couple of adjustments that should be tackled before we can merge this PR.

Also, I noticed that you're fetching the item data inside the `updateItem` function, which isn't necessary. Since we already have the latest data from the `useShoppingListData` custom hook, it would be more efficient to pass that data down to the Item component and then into the `updateItem` function. This way, we avoid redundant fetches,  making fewer API calls, which is always better for performance.

2024-09-14 15:50 UTC, redapy commented on src/api/firebase.js
> +				dateLastPurchased: Timestamp.fromDate(new Date()),
I believe it's enough to just have `new Date()` or the `today` variable you defined

2024-09-14 15:50 UTC, redapy commented on src/api/firebase.js
> +				),
you can use the helper function `getFutureDate` that you already have to convert the estimate to a javascript date

2024-09-14 15:50 UTC, redapy commented on src/api/firebase.js
> +			: today;
If the item has never been purchased, we should use the date it was created at instead of `today`

2024-09-14 15:50 UTC, redapy commented on src/components/ListItem.jsx
> +		const datePurchasedInMillis = datePurchased;
seems like the `?.toMillis` that got deleted here is causing the items to uncheck whenever the page refreshes, which is not the desired behavior

2024-09-15 10:56 UTC, redapy approved these changes

2024-09-15 15:29 UTC, merged