Relocate Share List func to modal + navigation to lists from Home + styled Home components
the-collab-lab/tcl-79-smart-shopping-list pull request #38
Opened 2024-10-04 17:28 UTC by Wyna-7

## Description

The share list functionality has been moved to a modal, which opens when the share button next to each list is clicked.
When a list name is clicked, the site navigates to the list view for that specific list.
Components visible from the home page have been styled to match Figma (as much as I could).

## Related Issue

Closes #32 

## Acceptance Criteria

- [x] Each `SingleList` component renders a button that allows the user to open a modal when clicked.
- [x] The modal allos the user to share the list with another user by filling and submitting a form.
- [x] Each `SingleList` component renders a clickable list name, which navigates to that list's view.
- [ ] - [x] Each `SingleList` component renders a delete list button that does nothing (for now :))

## Type of Changes

`enhancement`

## Updates

### Before

### After

![image](https://github.com/user-attachments/assets/4dc9cea7-2e86-49a4-a06f-cafaa747c2c3)
![image](https://github.com/user-attachments/assets/effd1be0-d3ca-4064-a982-e30a0955fdbd)

## Testing Steps / QA Criteria

- Do a `git pull` and `git checkout refactor_homepage`
- Open the homepage by running `npm start`.
- The share list functionality should be in a modal, which opens clicking the share icon next to each list.
- When clicking on a list name, the site should navigate to that list's view

2024-10-05 13:54 UTC, marshjaja requested changes
Well done! 🚀 I’ve made some suggested adjustments to align with the colour palette and design we chose on Figma.

There where a lot of file and I hope I didn't miss one😅
Please let me know if you have any questions

![Screenshot 2024-10-05 at 13 49 04](https://github.com/user-attachments/assets/601a5345-3815-4901-9538-a68c1e4a2260)
![Screenshot 2024-10-05 at 13 50 58](https://github.com/user-attachments/assets/c7a09608-975f-48b2-a03d-a0d5810b4c70)

2024-10-05 13:54 UTC, marshjaja commented on src/components/SingleList.jsx
> +		<li className="flex flex-row align-middle justify-between px-2 py-1 rounded-[5px] text-[1.2em] space-x-5 w-[16rem] bg-white text-black">
```suggestion
		<li className="flex flex-row align-middle justify-between px-2 py-3 rounded-[5px] text-[1.2em] space-x-5 w-full bg-white text-black">
```

2024-10-05 13:54 UTC, marshjaja commented on src/components/SingleList.jsx
> +				<button className="text-red-500  hover:text-red-600">
```suggestion
			<button className="text-pink-500  hover:text-pink-600">
					<RiDeleteBin5Fill size={24} />
				</button>
```

2024-10-05 13:54 UTC, marshjaja commented on src/views/Home.jsx
> +				<ul className="flex flex-col justify-center space-y-2">
```suggestion
				<ul className="flex flex-col justify-center space-y-4 w-full max-w-xl">
```

2024-10-05 13:54 UTC, marshjaja commented on src/views/Home.jsx
> +				<h1 className="font-[montserrat] font-bold text-[32px] underline decoration-solid decoration-4 decoration-[#2EBB4B]  ">
```suggestion
				<div className="relative inline-block">
					<h1 className=" font-[montserrat] text-3xl font-bold text-gray-300">
						<span className="relative inline-block">
							Your
							<span className="absolute bottom-[-6px] left-0 w-full h-[3px] bg-pink-500"></span>
						</span>{' '}
						Lists
					</h1>
				</div>
```

2024-10-05 13:54 UTC, marshjaja commented on src/components/ShareModal.jsx
> +		</div>
To be more inline with the Figma design I have added these classes

```suggestion
		<div className="fixed inset-0 flex justify-center items-center z-10">
			<div
				className="fixed inset-0 bg-[rgba(49,49,49,0.8)]"
				onClick={handleShareModalClick}
			></div>
			<div>
				<form
					onSubmit={(event) => handleSubmit(event)}
					className="relative text-black bg-slate-50 z-10 rounded p-10 w-full max-w-2xl  flex flex-col justify-between items-center space-y-6"
				>
					<h2 className="font-bold text-lg">You're sharing {name}</h2>
					<div className="w-full">
						<label htmlFor="email" className="block mb-2 text-sm">
							Invite a user by email:
						</label>
						<input
							className="w-full bg-white border-[1px] border-gray-400 focus-visible:outline-none focus:ring-1 focus:ring-green-500 rounded-xl p-2"
							type="text"
							id="email"
							required
							value={recipientEmail}
							onChange={(e) => setRecipientEmail(e.target.value)}
						/>
					</div>
					<div className="flex flex-row justify-center space-x-4 w-full">
						<button
							onClick={handleShareModalClick}
							className="bg-white  hover:bg-slate-100 hover:bg-opacity-80 py-62 px-8 border rounded-xl w-1/2"
						>
							Close
						</button>
						<button
							type="submit"
							className="bg-pink-500  hover:bg-pink-500 hover:bg-opacity-80  py-3 px-8 rounded-xl w-1/2"
						>
							Invite
						</button>
					</div>
				</form>
			</div>
		</div>
		
```

2024-10-05 13:54 UTC, marshjaja commented on src/components/CreateShoppingList.jsx
> +					className="border-[1px] rounded h-[3rem] hover:border-blue-700"
```suggestion
					className="border-[1px] rounded-lg h-[3rem] focus-visible:outline-none focus:ring-1 focus:ring-green-500"
```

2024-10-05 13:54 UTC, marshjaja commented on src/components/CreateShoppingList.jsx
> +				className="bg-[#FBB300] hover:bg-[#fbb400c9] text-black font-bold h-[3rem] p-3 rounded align-bottom"
```suggestion
	className="bg-green-500 hover:bg-green-500 hover:bg-opacity-80 text-black font-bold h-[3rem] p-3 rounded-lg align-bottom"
```

2024-10-06 04:50 UTC, Hudamabkhoot reviewed
Aside from the design notes from marcia it looks good to me great work! 👏

2024-10-06 12:09 UTC, marshjaja approved these changes

2024-10-06 12:41 UTC, merged