Mm feature/update listitem singlelist styling
the-collab-lab/tcl-79-smart-shopping-list pull request #51
Opened 2024-10-10 14:26 UTC by marshjaja

## Description
- This PR implements the styles defined in the Figma files for the `Home` and `List` pages, along with all accompanying files.
   - _Slightly reduced the layout width for the navbar on desktop view to ensure the `NavBar` is not too spaced out._
 

## Related Issue

Close #44, #47 

## Acceptance Criteria
The acceptance criteria for this PR are specified in [Issue #14](https://github.com/the-collab-lab/tcl-79-smart-shopping-list/issues/14).

## Type of Changes

Use one or more labels to help your team understand the nature of the change(s) you’re proposing. E.g., `bug fix` or `enhancement` are common ones.
`enhancement`
`fix`

## Updates

### Before

#### DESKTOP
<img src="https://github.com/user-attachments/assets/e02171f9-4433-47df-9623-299fc9341245" alt="Single List dark mode" width="200"/>
<img src="https://github.com/user-attachments/assets/a0a48b3f-5ae0-4b2c-a8a8-b6a100857426" alt="Your lists dark mode" width="200"/>
<img src="https://github.com/user-attachments/assets/d67e109b-46ad-41a4-880e-c3a8e6d40c5d" alt="Your list Light mode" width="200"/>
<img src="https://github.com/user-attachments/assets/995b3151-3109-415c-876c-50e3266b9f6cd" alt="Single List Light mode" width="200"/>
<img src="https://github.com/user-attachments/assets/21ee9920-ba96-408d-9bf3-3d776cfd35f5" alt="Screenshot 2024-10-10 at 15:08:02" width="100"/>
<img src="https://github.com/user-attachments/assets/c17cacaf-1830-4ff2-b031-05e39372f524" alt="Screenshot 2024-10-10 at 15:08:14" width="100"/>

----
----

### After

#### DESKTOP
<img src="https://github.com/user-attachments/assets/334896c6-e432-408c-9764-6eedb9516073" alt="Screenshot 2024-10-10 at 15:10:45" width="200"/>
<img src="https://github.com/user-attachments/assets/2b3ce742-f2d5-4303-9cea-f13ecb09552a" alt="Screenshot 2024-10-10 at 15:10:58" width="200"/>

#### MOBILE 
<img src="https://github.com/user-attachments/assets/1c507b5a-66e5-4b39-b435-44d1d8486097" alt="Screenshot 2024-10-10 at 14:55:03" width="200"/>
<img src="https://github.com/user-attachments/assets/42060b37-cae3-4dc1-9d13-f751d4b68d24" alt="Screenshot 2024-10-10 at 14:55:19" width="200"/>
<img src="https://github.com/user-attachments/assets/e340b387-0de5-4a5f-8d8c-c302e2cb6bdb" alt="Screenshot 2024-10-10 at 14:55:39" width="200"/>
<img src="https://github.com/user-attachments/assets/8dc35534-1099-432e-97e8-633650c20b93" alt="Screenshot 2024-10-10 at 14:55:57" width="200"/>
<img src="https://github.com/user-attachments/assets/80e7f82d-2f39-4a95-98b5-29803707915a" alt="Screenshot 2024-10-10 at 15:03:01" width="100"/>

## Testing Steps / QA Criteria

- Do a `git pull` and `git checkout mm-feature/update-listitem-singlelist-styling`
- On the `Home` and `List` pages you can see the styles implemented. You can toggle between Light mode and Dark mode to test the theme-switching functionality.

----
 Some styles might still need to be updated depending on the teams preference
 

 maybe adding some sort of background behind list to break out the white and black backgrounds.
 - examples (Not sure about the look):

<img src="https://github.com/user-attachments/assets/f96ea053-65db-4747-ab84-725ffe44a983" alt="" width="150"/>
<img src="https://github.com/user-attachments/assets/d73f56d6-2462-4d4c-a8e2-6c6a572455d1" alt="Screenshot 2024-10-10 at 16:11:11" width="150"/>
<img src="https://github.com/user-attachments/assets/3620b5fc-68d5-4491-83bd-eed0bb3de314" alt="Screenshot 2024-10-10 at 16:11:44" width="150"/>
<img src="https://github.com/user-attachments/assets/97502146-49c7-4416-a9d2-8dd6587a8271" alt="Screenshot 2024-10-10 at 16:13:46" width="150"/>

2024-10-11 10:53 UTC, Hudamabkhoot requested changes
looks amazing well done! I left a comment for you but I couldn't find this other thing in this pull request to comment on it but i think removing the label from the search bars would look better!

2024-10-11 10:53 UTC, Hudamabkhoot commented on src/views/Layout.jsx
> +					<main className="mx-auto px-8 md:px-8 lg:px-20 w-full max-w-screen-sm min-h-screen flex flex-col rounded-xl pt-20">
Adding bottom padding here would be good so main isn't covered by the nav bar when you scroll to the bottom

2024-10-11 12:26 UTC, joriordan332 requested changes
This looks brilliant! The only small thing I noticed and it's only on really small devices is that if the item name is a little longer like raspberries for example then the delete button doesn't stay within the box.
![Screenshot 2024-10-11 120831](https://github.com/user-attachments/assets/183fc6d2-714e-486b-a7a2-393f8cefc244)

2024-10-11 19:18 UTC, Wyna-7 approved these changes
It looks incredible, great job Marcia!
The only thing I would change is the position for the sign out and dark/light toggle buttons, I personally prefer the sign out one on the left. No biggie though!

2024-10-12 11:59 UTC, marshjaja commented
@Wyna-7 I have swap them around on mobile it does look better i hope this is want your meant?

2024-10-12 12:00 UTC, marshjaja commented
@joriordan332 very good spot this one Jonathan👏🏾, forgot to check!

2024-10-12 12:02 UTC, marshjaja commented
@Hudamabkhoot  for the labels I can't remove them for accessibility reason. I have added button padding very good spot!🤾🏾‍♀️

2024-10-12 12:27 UTC, joriordan332 approved these changes

2024-10-12 12:30 UTC, Hudamabkhoot approved these changes

2024-10-12 12:41 UTC, merged